App_Blog/urls.py
from django.urls import path
from . import views
from .views import CreateBlog, BlogList, MyBlogs, UpdateBlog

app_name = 'App_Blog'

urlpatterns = [
    path('', BlogList.as_view(), name='blog-home'),
    path('blog_create/', CreateBlog.as_view(), name='blog-create'),
    path('my_blogs/', MyBlogs.as_view(), name='my-blogs'),
    path('blog_details/<slug:slug>/', views.blog_details, name='blog-details'),
    path('blog_edit/<int:pk>/', UpdateBlog.as_view(), name='blog-edit'),
    path('blog_delete/<int:pk>/', views.blog_delete, name='blog-delete'),
    path('comment_delete/<int:pk>/', views.comment_delete, name='comment-delete'),
    path('liked/<int:pk>/', views.liked, name='blog-liked'),
    path('unliked/<int:pk>/', views.unliked, name='blog-unliked'),
]

App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('register/', views.register, name='blog-register'),
    path('login/', views.login_page, name='blog-login'),
    path('logout/', views.logout_page, name='blog-logout'),
    path('profile/', views.profile, name='blog-profile'),
    path('update_profile/', views.update_profile, name='blog-update-profile'),
    path('change_password/', views.change_password, name='blog-change-password')

]

Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include

# For Media
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Blog.urls')),
    path('', include('App_Login.urls')),

    path('password_reset/',
    auth_views.PasswordResetView.as_view(template_name='App_Login/password_reset.html'),
    name='password_reset'),

    path('password_reset/done/',
    auth_views.PasswordResetDoneView.as_view(template_name='App_Login/password_reset_done.html'),
    name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/',
    auth_views.PasswordResetConfirmView.as_view(template_name='App_Login/password_reset_confirm.html'),
    name='password_reset_confirm'),

    path('password_reset_complete/',
    auth_views.PasswordResetCompleteView.as_view(template_name='App_Login/password_reset_complete.html'),
    name='password_reset_complete')
]

# For Media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    image = models.ImageField(default='default.png',upload_to='profile_pics')

    def __str__(self):
        return self.user.username

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import UserProfile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(label='Email Address')
    class Meta:
        model  = User
        fields = ['username', 'email', 'password1', 'password2']


class UserProfileChangeForm(forms.ModelForm):
    email = forms.EmailField(label='Email Address')

    class Meta:
        model  = User
        fields = ['username', 'email', 'first_name', 'last_name']


class ChangeProfilePicForm(forms.ModelForm):
    class Meta:
        model  = UserProfile
        fields = ['image']



# class UserProfileChangeForm(UserChangeForm):
#     password = None
#     class Meta:
#         model = User
#         fields = ('username', 'email', 'first_name', 'last_name')


# class ChangeProfilePic(forms.ModelForm):
#     class Meta:
#         model = UserProfile
#         fields = ['image']

App_Login/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from .forms import (
    UserRegisterForm, 
    UserProfileChangeForm, 
    ChangeProfilePicForm
    )
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required

def register(request):
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        form.save()
        username = form.cleaned_data.get('username')
        messages.success(request, f'Account successfully created for {username}')
        return redirect('App_Login:blog-login')
    context = {
        'form' : form
    }
    return render(request, 'App_Login/register.html', context)

def login_page(request):
    form = AuthenticationForm(data=request.POST or None)
    if form.is_valid():
         username = form.cleaned_data.get('username')
         password = form.cleaned_data.get('password')
         user = authenticate(request, username=username, password=password)
         if user is not None:
             login(request, user)
             messages.success(request, f'{username} Login Successfully')
             return redirect('App_Blog:blog-home')
    context = {
        'form' : form
    }
    return render(request, 'App_Login/login.html', context)


@login_required
def logout_page(request):
    messages.success(request, f'{request.user.username} Logout Successfully. Log In Again...')
    logout(request)
    return redirect('App_Login:blog-login')


@login_required
def profile(request):
    return render(request, 'App_Login/profile.html')

@login_required
def change_password(request):
    current_user = request.user
    form = PasswordChangeForm(current_user, data=request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, "Your Password Have Changed...✅ Login Again")
        return redirect('App_Login:blog-profile')

    context = {
        'form' : form
    }
    return render(request, 'App_Login/change_password.html', context)


@login_required
def update_profile(request):
    if request.method == 'POST':
        u_form = UserProfileChangeForm(request.POST, instance=request.user)
        p_form = ChangeProfilePicForm(request.POST, 
        request.FILES,
        instance=request.user.user_profile
        )
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Your Profile has Updated...✅')
            return redirect('App_Login:blog-profile')
    else:
        u_form = UserProfileChangeForm(instance=request.user)
        p_form = ChangeProfilePicForm(instance=request.user.user_profile)

    context = {
        'u_form' : u_form,
        'p_form' : p_form
    }
    return render(request, 'App_Login/change_profile.html', context)

App_Login/templates/App_Login/change_password.html
{% extends 'App_Blog/base.html' %} 
{% block title %}-Change Password{% endblock title%} 
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Change Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group mt-3 mb-3">
            <button class="btn btn-outline-warning" type="submit"> Change </button>
        </div>
    </form>
{% endblock content %}

App_Login/templates/App_Login/change_profile.html
{% extends 'App_Blog/base.html' %} 
{% block title %}-Change Profile{% endblock title%} 
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Update Profile</legend>
            {{ u_form|crispy }}
            {{ p_form|crispy }}
        </fieldset>
        <div class="form-group mt-3 mb-3">
            <button class="btn btn-outline-info" type="submit"> Update </button>
        </div>
    </form>
{% endblock content %}

App_Login/templates/App_Login/login.html
{% extends 'App_Blog/base.html' %} 
{% block title %}-Login{% endblock title%} 
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group mt-3 mb-3">
            <button class="btn btn-outline-info" type="submit"> Login </button>
            <small class="text-muted ml-2">
                <a href="{% url 'password_reset' %}">Forgot Password?</a>
            </small>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{% url 'App_Login:blog-register' %}">Sing Up Now</a>
        </small>
    </div>
{% endblock content %}

App_Login/templates/App_Login/password_reset.html
{% extends 'App_Blog/base.html' %} 
{% block title %}-Request Reset{% endblock title%} 
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group mt-3 mb-3">
            <button class="btn btn-outline-info btn-sm" type="submit"> Request Password Reset </button>
        </div>
    </form>
{% endblock content %}

App_Login/templates/App_Login/password_reset_complete.html
{% extends 'App_Blog/base.html' %} 
{% block title %}-Reset Mail{% endblock title%} 

{% block content %}
    <div class="alert alert-info">
        Your Password Has been set.✅
    </div>
    <a href="{% url 'App_Login:blog-login'%}">Sing In Here...</a>
{% endblock content %}

App_Login/templates/App_Login/password_reset_confirm.html
{% extends 'App_Blog/base.html' %} 
{% block title %}-Password Reset{% endblock title%} 
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Paaword Reset</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group mt-3 mb-3">
            <button class="btn btn-outline-info btn-sm" type="submit"> Password Reset </button>
        </div>
    </form>
{% endblock content %}

App_Login/templates/App_Login/password_reset_done.html
{% extends 'App_Blog/base.html' %} 
{% block title %}-Reset Mail{% endblock title%} 

{% block content %}
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password...
    </div>
{% endblock content %}

App_Login/templates/App_Login/profile.html
{% extends 'App_Blog/base.html' %}
{% block title %}-Profile{% endblock title%}
{% block content %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-xl-6 col-md-12">
                <div class="card user-card-full">
                    <div class="row m-l-0 m-r-0">
                        <div class="col-sm-4 bg-c-lite-green user-profile">
                            <div class="card-block text-center text-white">
                                <div class="m-b-25">
                                    <img src="{{ user.user_profile.image.url }}" class="img-radius" alt="User-Profile-Image">
                                </div>
                                <h6 class="f-w-600">{{user.username}}</h6>
                                <p>Web Designer</p> <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="card-block">
                                <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Information</h6>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">First Name</p>
                                        <h6 class="text-muted f-w-400">
                                            {% if user.first_name %}
                                                {{user.first_name}}
                                            {% else %}
                                                NULL
                                            {% endif %}
                                        </h6>
                                    </div>
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Last Name</p>
                                        <h6 class="text-muted f-w-400">
                                            {% if user.last_name %}
                                                {{user.last_name}}
                                            {% else %}
                                                NULL
                                            {% endif %}
                                        </h6>
                                    </div>
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Email</p>
                                        <h6 class="text-muted f-w-400">
                                            {% if user.email %}
                                                {{user.email}}
                                            {% else %}
                                                NULL
                                            {% endif %}
                                        </h6>
                                    </div>
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Phone</p>
                                        <h6 class="text-muted f-w-400">Coming...🕖</h6>
                                    </div>
                                </div>
                                <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600">Projects</h6>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Recent</p>
                                        <h6 class="text-muted f-w-400">Coming...🕜</h6>
                                    </div>
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Most Viewed</p>
                                        <h6 class="text-muted f-w-400">Coming...🕒</h6>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-6 mt-4">
                                        <a class="btn btn-info" href="{% url 'App_Login:blog-update-profile' %}">Update Profile</a>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

App_Login/templates/App_Login/register.html
{% extends 'App_Blog/base.html' %} 
{% block title %}-Register{% endblock title%} 
{% load crispy_forms_tags %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Registration Form</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group mt-4 mb-4">
            <button class="btn btn-outline-info" type="submit"> Sing Up </button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{% url 'App_Login:blog-login'%}">Sing In</a>
        </small>
    </div>
{% endblock content %}