App_Blog/urls.py
from django.urls import path
from . import views
from .views import CreateBlog, BlogList, MyBlogs, UpdateBlog

app_name = 'App_Blog'

urlpatterns = [
    path('', BlogList.as_view(), name='blog-home'),
    path('blog_create/', CreateBlog.as_view(), name='blog-create'),
    path('my_blogs/', MyBlogs.as_view(), name='my-blogs'),
    path('blog_details/<slug:slug>/', views.blog_details, name='blog-details'),
    path('blog_edit/<int:pk>/', UpdateBlog.as_view(), name='blog-edit'),
    path('blog_delete/<int:pk>/', views.blog_delete, name='blog-delete'),
    path('comment_delete/<int:pk>/', views.comment_delete, name='comment-delete'),
    path('liked/<int:pk>/', views.liked, name='blog-liked'),
    path('unliked/<int:pk>/', views.unliked, name='blog-unliked'),
]

App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('register/', views.register, name='blog-register'),
    path('login/', views.login_page, name='blog-login'),
    path('logout/', views.logout_page, name='blog-logout'),
    path('profile/', views.profile, name='blog-profile'),
    path('update_profile/', views.update_profile, name='blog-update-profile'),
    path('change_password/', views.change_password, name='blog-change-password')

]

Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include

# For Media
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App_Blog.urls')),
    path('', include('App_Login.urls')),

    path('password_reset/',
    auth_views.PasswordResetView.as_view(template_name='App_Login/password_reset.html'),
    name='password_reset'),

    path('password_reset/done/',
    auth_views.PasswordResetDoneView.as_view(template_name='App_Login/password_reset_done.html'),
    name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/',
    auth_views.PasswordResetConfirmView.as_view(template_name='App_Login/password_reset_confirm.html'),
    name='password_reset_confirm'),

    path('password_reset_complete/',
    auth_views.PasswordResetCompleteView.as_view(template_name='App_Login/password_reset_complete.html'),
    name='password_reset_complete')
]

# For Media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
    author       = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    title        = models.CharField(max_length=264, verbose_name='Put a title')
    slug         = models.SlugField(max_length=264, unique=True)
    content      = models.TextField(verbose_name="What's on your mind?")
    blog_image   = models.ImageField(upload_to='blog_images', verbose_name='Image')
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date  = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-publish_date']

class Comment(models.Model):
    blog         = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user         = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment      = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment[:30] + "..."

    class Meta:
        ordering = ['-comment_date']
        

class Like(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='liked_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker_user')

    def __str__(self):
        return self.user.username + " Likes " + self.blog.title

App_Blog/forms.py
from django import forms
from .models import Blog, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

App_Blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from .models import Blog, Comment, Like
from django.views.generic import (
    CreateView,
    ListView,
    TemplateView,
    UpdateView
    )
import uuid
from .forms import CommentForm

class BlogList(ListView):
    model               = Blog
    context_object_name = 'blogs'
    template_name       = 'App_Blog/blog_list.html'
    paginate_by         = 2
    # queryset            = Blog.objects.order_by('-publish_date')
  

class CreateBlog(LoginRequiredMixin, CreateView):
    model         = Blog
    template_name = 'App_Blog/blog_create.html'
    fields        = ['title', 'content', 'blog_image']

    def form_valid(self, form):
        blog_obj        = form.save(commit=False)
        blog_obj.author = self.request.user
        title           = blog_obj.title
        blog_obj.slug   = title.replace(" ", "-") + "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('App_Blog:blog-home'))

@login_required
def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)
    form = CommentForm(request.POST or None)
    already_liked = Like.objects.filter(blog=blog, user=request.user)
    if already_liked:
        liked = True
    else:
        liked = False

    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.blog = blog
        comment.save()
        messages.success(request, 'Your comment post successfully...🚀')
        return HttpResponseRedirect(reverse('App_Blog:blog-details', kwargs={'slug':slug}))

    context = {
        'blog' : blog,
        'form' : form,
        'liked': liked
    }
    return render(request, 'App_Blog/blog_details.html', context)


@login_required
def liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(blog=blog, user=user)
    if not already_liked:
        liked_post = Like(blog=blog, user=user)
        liked_post.save()
    return HttpResponseRedirect(reverse('App_Blog:blog-details', kwargs={'slug': blog.slug})) 


@login_required
def unliked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('App_Blog:blog-details', kwargs={'slug': blog.slug}))



class MyBlogs(LoginRequiredMixin, TemplateView):
    template_name = 'App_Blog/my_blogs.html'


class UpdateBlog(LoginRequiredMixin, UpdateView):
    model  = Blog
    fields = ['title', 'content', 'blog_image']
    template_name = 'App_Blog/blog_edit.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('App_Blog:blog-details', kwargs={'slug' : self.object.slug}) #not reverse till update


def blog_delete(request, pk):
    blog = Blog.objects.get(pk=pk)
    blog.delete()
    messages.warning(request, 'Your Blog Deleted Successfully!')
    return HttpResponseRedirect(reverse('App_Blog:my-blogs'))


def comment_delete(request, pk):
    comment = Comment.objects.get(pk=pk)
    slug = comment.blog.slug
    comment.delete()
    messages.warning(request, 'Your Comment  Deleted Successfully!')
    return HttpResponseRedirect(reverse('App_Blog:blog-details', kwargs={'slug': slug}))

App_Blog/templates/App_Blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'App_Login/css/main.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'App_Blog/css/main.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Blog{% block title %}{% endblock title %}</title>
    {% block css %}{% endblock css %}
</head>
<body>

    {% include 'App_Blog/navber.html' %}

    <div class="container mt-4">

        {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }} mt-2 mt-2">
                  {{message}}
                </div>
              {% endfor %}
        {% endif %}

        {% block content %} {% endblock content %}

    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

App_Blog/templates/App_Blog/blog_create.html
{% extends 'App_Blog/base.html' %} 
{% block title %}-Create Blog{% endblock title%} 
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create Blog</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group mt-3 mb-3">
            <button class="btn btn-outline-info btn-sm" type="submit"> Submit </button>
        </div>
    </form>
{% endblock content %}

App_Blog/templates/App_Blog/blog_details.html
{% extends 'App_Blog/base.html' %}
{% load static %}
{% block title %}-Details{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}

<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ blog.author.user_profile.image.url }}" alt="">
    <div class="media-body">
        <div class="article-metadata">

            <b>{{ blog.author }}</b><br>
            <small class="text-muted">Publish Date: <b>{{ blog.publish_date|date:"F d, Y" }}</b></small>
            <small class="text-muted">Update Date:  <b>{{ blog.update_date|date:"F d, Y" }}</b></small><br>
            <h6 class="mt-2">{{ blog.liked_blog.count }} Like{{ blog.liked_blog.count|pluralize }}</h6>
            <h6>{{blog.blog_comment.count}} Comment{{blog.blog_comment.count|pluralize}}</h6>

            {% if request.user.is_authenticated and blog.author == user %}
            <a class="btn btn-primary btn-sm mb-4 mt-4" href="{% url 'App_Blog:blog-edit' pk=blog.pk%}">Edit</a>
            <a class="btn btn-danger btn-sm mb-4 mt-4" href="{% url 'App_Blog:blog-delete' pk=blog.pk%}">Delete</a>
            {% endif %}
        </div>
        <h2>{{ blog.title }}</h2>
        <div class="row">
            <div class="col-sm-4">
                <img class="blog-img" src="{{ blog.blog_image.url }}" alt="">
            </div>
            <div class="col-sm-8">
                <p class="article-content">{{ blog.content|linebreaks }}</p>
            </div>
        </div>
        <div class="mt-2">
          {% if not liked %}
            <a href="{% url 'App_Blog:blog-liked' pk=blog.pk %}"><img class="like-img" src="{% static 'App_Blog/images/like.png'%}" alt=""></a>
          {% else %}
            <a href="{% url 'App_Blog:blog-unliked' pk=blog.pk %}"><img class="like-img" src="{% static 'App_Blog/images/dislike.png'%}"  alt=""></a>
          {% endif %}
        </div>
    </div>
</article>


<hr>
<div class="row">
  <div class="col-sm-6">
    <h5>Comments</h5>
    {% for comment in blog.blog_comment.all %}

      <p><a href="">{{comment.user.username}}</a></p>
      <p>{{comment.comment_date}}</p>
      <p>{{comment.comment}}</p>

      {% if request.user.is_authenticated and request.user.username == comment.user.username %}
      <a class="btn btn-danger btn-sm" href="{% url 'App_Blog:comment-delete' pk=comment.pk%}">Delete</a>
      {% endif %}
      <hr>

    {% endfor %}
  </div>
  <div class="col-sm-6">
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          {{ form|crispy }}
      </fieldset>
      <div class="form-group mt-3 mb-3">
          <button class="btn btn-outline-primary" type="submit"> submit </button>
      </div>
  </form>
  </div>
</div>

{% endblock content %}

App_Blog/templates/App_Blog/blog_edit.html
{% extends 'App_Blog/base.html' %} 
{% block title %}-Update Blog{% endblock title%} 
{% load crispy_forms_tags %}

{% block content %}
{% if blog.author == user %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Update Blog</legend>
        {{ form|crispy }}
    </fieldset>
    <div class="form-group mt-3 mb-3">
        <button class="btn btn-outline-info btn-sm" type="submit"> Submit </button>
    </div>
</form>
{% else %}
<h3>You are not allowed buddy....</h3>
{% endif %}
    
{% endblock content %}

App_Blog/templates/App_Blog/blog_list.html
{% extends 'App_Blog/base.html' %}
{% block title %}-Home{% endblock title %}
{% block content %}

{% for blog in blogs %}

<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ blog.author.user_profile.image.url }}" alt="">
    <div class="media-body">
        <div class="article-metadata">
            <b>{{ blog.author }}</b><br>
            <small class="text-muted">{{ blog.publish_date|date:"F d, Y" }}</small><br>
            <h6 class="mt-2">{{ blog.liked_blog.count }} Like{{ blog.liked_blog.count|pluralize }}</h6>
            <h6>{{blog.blog_comment.count}} Comment{{blog.blog_comment.count|pluralize}}</h6>

        </div>
        <h2><a class="article-title" href="{% url 'App_Blog:blog-details' slug=blog.slug %}">{{ blog.title }}</a></h2>
        <div class="row">
            <div class="col-sm-4">
                <img class="blog-img" src="{{ blog.blog_image.url }}" alt="">
            </div>
            <div class="col-sm-8">
                <p class="article-content">{{ blog.content|linebreaks|truncatewords:30 }}</p>
            </div>
        </div>
    </div>
</article>
{% endfor %}

{% if is_paginated %}

        {% if page_obj.has_previous %}

            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>

        {% endif %}

        {% for num in page_obj.paginator.page_range %}

            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>

            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>

            {% endif %}

        {% endfor %}

        {% if page_obj.has_next %}

            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>

        {% endif %}

    {% endif %}

{% endblock content %}

App_Blog/templates/App_Blog/my_blogs.html
{% extends 'App_Blog/base.html' %}
{% block title %}-My Blogs{% endblock title %}
{% block content %}

<h2>Your Total Blogs: {{user.post_author.count}}</h2>

{% for blog in user.post_author.all %}

<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ blog.author.user_profile.image.url }}" alt="">
    <div class="media-body">
        <div class="article-metadata">

            <b>{{ blog.author }}</b><br>
            <small class="text-muted">{{ blog.publish_date|date:"F d, Y" }}</small><br>
            <h6 class="mt-2">{{ blog.liked_blog.count }} Like{{ blog.liked_blog.count|pluralize }}</h6>
            <h6>{{blog.blog_comment.count}} Comment{{blog.blog_comment.count|pluralize}}</h6>

            {% if blog.author == user %}
            <a class="btn btn-primary btn-sm" href="{% url 'App_Blog:blog-edit' pk=blog.pk%}">Edit</a>
            <a class="btn btn-danger btn-sm" href="{% url 'App_Blog:blog-delete' pk=blog.pk%}">Delete</a>
            {% endif %}

        </div>
        <h2><a class="article-title" href="{% url 'App_Blog:blog-details' slug=blog.slug %}">{{ blog.title }}</a></h2>
        <div class="row">
            <div class="col-sm-4">
                <img class="blog-img" src="{{ blog.blog_image.url }}" alt="">
            </div>
            <div class="col-sm-8">
                <p class="article-content">{{ blog.content|linebreaks|truncatewords:30 }}</p>
            </div>
        </div>
    </div>
</article>

{% endfor %}

{% endblock content %}

App_Blog/templates/App_Blog/navber.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'App_Blog:blog-home'%}">Django-Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'App_Blog:blog-home'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'App_Blog:blog-create'%}">Write Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'App_Blog:my-blogs'%}">My Blogs</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{user.username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" aria-current="page" href="{% url 'App_Login:blog-profile'%}">Profile</a>
              <a class="dropdown-item" aria-current="page" href="{% url 'App_Login:blog-change-password'%}">Change Password</a>
              <a class="dropdown-item" aria-current="page" href="{% url 'App_Login:blog-logout'%}">Logout</a>
            </div>
          </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'App_Login:blog-login'%}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'App_Login:blog-register'%}">Register</a>
            </li>
          {% endif %}
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-warning" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>